-- MySQL Script generated by MySQL Workbench
-- Sun Oct 19 19:12:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmacia` DEFAULT CHARACTER SET utf8 ;
USE `farmacia` ;

-- -----------------------------------------------------
-- Table `farmacia`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Persona` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Trabajador` (
  `id` VARCHAR(45) NOT NULL,
  `gafete` VARCHAR(45) NOT NULL,
  `claveSistema` VARCHAR(45) NOT NULL,
  INDEX `fk_Trabajador_Persona_idx` (`id` ASC) VISIBLE,
  PRIMARY KEY (`gafete`),
  CONSTRAINT `fk_Trabajador_Persona`
    FOREIGN KEY (`id`)
    REFERENCES `farmacia`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Medico` (
  `especialidad` VARCHAR(45) NULL,
  `gafete` VARCHAR(45) NOT NULL,
  INDEX `fk_Medico_Trabajador1_idx` (`gafete` ASC) VISIBLE,
  CONSTRAINT `fk_Medico_Trabajador1`
    FOREIGN KEY (`gafete`)
    REFERENCES `farmacia`.`Trabajador` (`gafete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Paciente` (
  `id` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `fechaNac` DATE NULL,
  INDEX `fk_Paciente_Persona1_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_Persona1`
    FOREIGN KEY (`id`)
    REFERENCES `farmacia`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Farmaceuta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Farmaceuta` (
  `gafete` VARCHAR(45) NOT NULL,
  INDEX `fk_Farmaceuta_Trabajador1_idx` (`gafete` ASC) VISIBLE,
  CONSTRAINT `fk_Farmaceuta_Trabajador1`
    FOREIGN KEY (`gafete`)
    REFERENCES `farmacia`.`Trabajador` (`gafete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Medicamento` (
  `codigo` VARCHAR(45) NOT NULL,
  `presentacion` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`Receta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paciente` VARCHAR(45) NOT NULL,
  `fechaConfeccion` DATE NULL,
  `fechaRetiro` DATE NULL,
  `estado` VARCHAR(45) NULL,
  INDEX `fk_Receta_Persona1_idx` (`paciente` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Receta_Persona1`
    FOREIGN KEY (`paciente`)
    REFERENCES `farmacia`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`MedicamentoRecetado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`MedicamentoRecetado` (
  `prescripcion` INT NOT NULL,
  `medicamento` VARCHAR(45) NOT NULL,
  `cantidad` INT NULL,
  `indicaciones` VARCHAR(45) NULL,
  `duracionDias` INT NULL,
  INDEX `fk_MedicamentoRecetado_Medicamento1_idx` (`medicamento` ASC) VISIBLE,
  INDEX `fk_MedicamentoRecetado_Receta1_idx` (`prescripcion` ASC) VISIBLE,
  CONSTRAINT `fk_MedicamentoRecetado_Medicamento1`
    FOREIGN KEY (`medicamento`)
    REFERENCES `farmacia`.`Medicamento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MedicamentoRecetado_Receta1`
    FOREIGN KEY (`prescripcion`)
    REFERENCES `farmacia`.`Receta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- ====================================
-- TABLA DE MENSAJES
-- ====================================

CREATE TABLE IF NOT EXISTS Mensaje (
    id INT AUTO_INCREMENT PRIMARY KEY,
    remitenteId VARCHAR(50) NOT NULL,
    remitenteNombre VARCHAR(100) NOT NULL,
    destinatarioId VARCHAR(50) NOT NULL,
    destinatarioNombre VARCHAR(100) NOT NULL,
    contenido TEXT NOT NULL,
    fecha DATETIME NOT NULL,
    leido BOOLEAN DEFAULT FALSE,
    
    -- Índices para mejorar el rendimiento
    INDEX idx_destinatario (destinatarioId),
    INDEX idx_leido (leido),
    INDEX idx_fecha (fecha DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Verificar que se creó correctamente
DESCRIBE Mensaje;

-- (Opcional) Insertar mensaje de prueba
INSERT INTO Mensaje (remitenteId, remitenteNombre, destinatarioId, destinatarioNombre, contenido, fecha, leido)
VALUES ('admin', 'Administrador', '123', 'Juan Pérez', 'Bienvenido al sistema', NOW(), FALSE);

-- Ver mensajes
SELECT * FROM Mensaje;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
